export const INDEX_TYPE = {
  DICTIONARY: 'DICTIONARY',
  FULLTEXT: 'FULLTEXT',
  UNIQUE: 'UNIQUE',
  NOTUNIQUE: 'NOTUNIQUE',
  DICTIONARY_HASH_INDEX: 'DICTIONARY_HASH_INDEX',
  FULLTEXT_HASH_INDEX: 'FULLTEXT_HASH_INDEX',
  UNIQUE_HASH_INDEX: 'UNIQUE_HASH_INDEX',
  NOTUNIQUE_HASH_INDEX: 'NOTUNIQUE_HASH_INDEX'
};
